name: Update the documentation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  
jobs:
  generateDocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

          echo $list | grep README.md

      # - name: Check PR
      #   uses: JJ/github-pr-contains-action@releases/v4
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     diffContains: 'README.md'

      # - name: Get changes
      #   run: git diff --name-only -r HEAD^1 HEAD

