name: Update the documentation

on:
  pull_request:
    # types:
    #   - closed

permissions:
  contents: write
  pull-requests: write
  
jobs:
  generateDocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v0
        with:
          github-token: ${{github.token}}
          diffContains: 'README.md'

      # - name: Get changes
      #   run: git diff --name-only -r HEAD^1 HEAD

